### ISSUE TITLE
How to change the face color?

### ISSUE THREAD

**Issue by olmokramer** [syl20bnr/vi-tilde-fringe#6]
I'm quite new to Emacs, and I've searched a bit, but I can't seem to change the color of the tildes. I've tried these methods, but none of them work. What am I doing wrong?
```elisp
;; Doesn't change anything
(set-face-attribute 'vi-tilde-fringe-face nil :inherit 'font-lock-comment-face)

;; Doesn't do anything
(set-fringe-bitmap-face 'vi-tilde-fringe-bitmap 'font-lock-comment-face)

;; Auto generated by customize-group, but doesn't do anything
(custom-set-faces
 '(vi-tilde-fringe-face ((t (:inherit (quote font-lock-comment-face))))))
```
The snippet from the reddit page does work, however, but I like this to be a minor mode because I don't need it when writing plain text.

**Comment by olmokramer** [comment]
Ok, I've found a solution: `(set-fringe-bitmap-face 'vi-tilde-fringe-bitmap 'font-lock-comment-face)` actually *does* work, it just doesn't redraw the already drawn tildes. After scrolling them out of view and srolling back down they have changed to the comment face.

**Comment by olmokramer** [comment]
Never mind, the above only works when I eval it during runtime, but it doesn't work when I put it in my `init.el`.

**Comment by olmokramer** [comment]
Ok, so now it *does* work from my `init.el`... Don't know what I changed...

**Comment by mddavila** [comment]
Face color changes are not working right now, I had to changed to [vim-empty-lines-mode](https://github.com/jmickelin/vim-empty-lines-mode). Here is my configuration with [quelpa-use-package](https://framagit.org/steckerhalter/quelpa-use-package) and [use-package](https://github.com/jwiegley/use-package) with `(setq use-package-always-defer t)` previously included in my init file:

```
(use-package vim-empty-lines-mode
  :quelpa (vim-empty-lines-mode
	   :fetcher github
	   :repo "jmickelin/vim-empty-lines-mode")
  :hook (prog-mode . vim-empty-lines-on)
  :config
  (require 'vim-empty-lines-off)
  (custom-set-faces
   '(vim-empty-lines-face ((t
			    (:inherit
			     (linum)))))))
```
